Made PingPoll more clear
codeman1o1/TIJK-Bot pull request #252
Opened 2022-09-11 15:47 UTC by JustIanJ

# Summary

## Checklist

- [ ] If code changes were made then they have been tested
- [ ] This PR improves a feature
- [ ] This PR adds a feature
  - [ ] This PR adds a slash command
  - [ ] This PR adds a view
  - [ ] This PR adds a cog
- [ ] This PR fixes an issue
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-09-11 15:48 UTC, codeman1o1 commented
Please add a summary.

2022-09-11 15:49 UTC, JustIanJ commented
It was not clear what i should have done the first time i used it

2022-09-11 15:50 UTC, JustIanJ commented
> Please add a summary.

i did just now

2022-09-11 15:51 UTC, codeman1o1 commented
> > Please add a summary.
> 
> i did just now

In the first message please

2022-09-19 19:15 UTC, codeman1o1 requested changes

2022-09-19 19:15 UTC, codeman1o1 commented on views/dropdowns/pingpoll_time.py
> +            placeholder="Please select how long the PingPoll should stay.",
Please remove the dot at the end of the sentence
```suggestion
            placeholder="Please select how long the PingPoll should stay",
```

2022-09-23 16:49 UTC, codeman1o1 approved these changes
LGTM

2022-09-26 13:51 UTC, codeman1o1 commented
I don't know whether _choose_ or _select_ would be better here.
What is your opinion @JustIanJ?

2022-09-26 20:45 UTC, JustIanJ commented
I chose the current one in my branch with a reason

2022-09-26 20:48 UTC, codeman1o1 commented
> with a reason

What is the reason if I may ask?

2022-09-26 20:51 UTC, JustIanJ commented
Because select suggest (to me) that there are a (fairly) limited amount of possible options.
Choose is like a ton of options

2022-09-26 20:55 UTC, codeman1o1 commented
Makes sense yeah

2022-09-26 20:58 UTC, merged